apiVersion: v1
kind: Service
metadata:
  name: itemsearch-svc
  labels:
    app: itemreservation-msa
spec:
  #type: NodePort --removed for GCP and Added 'type: LoadBalancer'
  type: LoadBalancer 
  ports:
  - port: 8091 
    targetPort: 8091
    protocol: TCP 
    #nodePort: 31091 -- removed for GCP and Added protocol:TCP 
  selector:
    app: itemreservation-msa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: itemsearch-svc
spec:
  selector:
    matchLabels:
      app: itemreservation-msa
  replicas: 1
  template:
    metadata:
      labels:
        app: itemreservation-msa
    spec:
      containers:
      - name: itemsearch
        image: docker.io/debanjande/ora-itemsearch-v1
        #resources:
        #  requests:
        #    cpu: 100m
        #    memory: 100Mi
        ports:
        - containerPort: 8091
